name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      # Since GITHUB_TOKEN will not trigger manifest.yml, generate a replacement
      - name: Generate Access Token
        uses: actions/create-github-app-token@v3
        id: access
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          token: ${{ steps.access.outputs.token }}
          # Prevents the usage of GITHUB_TOKEN
          persist-credentials: false
          # Changesets needs the complete Git history
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          cache: true

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to NPM
        # Forked to correctly handle `changeset publish --no-git-tag`
        uses: luisbs/changesets-action@v1
        id: changesets
        with:
          title: "chore: release @luis.bs/obsidian-attachments-cache"
          commit: "chore: release @luis.bs/obsidian-attachments-cache"
          publish: pnpm run ci:publish
          noGitTags: true
          createGithubReleases: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ steps.access.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        # Reverse what clean-pkg-json did before publishing
        run: |
          git reset --hard HEAD
          pnpm run ci:obsidian
        env:
          GH_TOKEN: ${{ steps.access.outputs.token }}
